services:
  mysql:
    image: mysql:8.4
    container_name: ms-proveedores-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mayorista_proveedores
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: ms_proveedores_app
      MYSQL_PASSWORD: ms_proveedores_app1234
    ports:
      - "3312:3306"
    volumes:
      - mysql_data_proveedores:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .    #el contedor va a buldear la imagen  del Dockerfile, que se encuentra en el directorio raíz del proyecto
    container_name: ms-proveedores-app
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy


      #variables de entorno para la conexión a la base de datos, que se pasan al contenedor de la aplicación
      #se usa el nombre del servicio "mysql" como host porque ambos contenedores estan en la misma red de docker-compose

    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mayorista_proveedores
      - SPRING_DATASOURCE_USERNAME=ms_proveedores_app
      - SPRING_DATASOURCE_PASSWORD=ms_proveedores_app1234
      - SERVER_PORT=8089
    ports:
      - "8089:8089"

      #volumes: para ocupar la configuración por defecto

volumes:
  mysql_data_proveedores: