# nombre de la aplicacion
spring.application.name=proveedor

# puerto en el que corre este microservicio
server.port=8089

# cambio clave: localhost reemplazado por host.docker.internal
# esto permite que Docker encuentre el MySQL de tu PC
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/mayorista_proveedores
spring.datasource.username=root
spring.datasource.password=

# credenciales de Spring Security
spring.security.user.name=admin
spring.security.user.password=12347

# configuracion de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# url del microservicio 
proveedores.service.url=http://host.docker.internal:8089